name: Build & Depoly
on: 
 push:
   branches:
     - main
 pull_request:
   types: 
     - opened
     - synchronize
jobs:
  build:
   runs-on: ubuntu-latest
   if: github.event_name == 'pull_request'
   steps:
     - name: Build Step
       run: echo "Build the application"
  depoly:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'name'
    steps:
      - name: Depoly Step
        run: echo "Depolying the app"
