name: Context Demo
on: push
jobs:
  context-demo:
     runs-on: ubuntu-latest
     steps:
       - name: Use context variables
         run: |
           echo "This workflow is triggered by ${{ github.actor }}"
           echo "The repository name is  ${{ github.repository }}"

       - name: Print all variable under github
         run: echo "${{toJson(github)}}"

       - name: Print enviroment variable
         run: echo "$GITHUB_SHA"
           
           
