name: Outputs Demo
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        id: step1
        run: echo "This version=0.0.1" >> $GITHUB_OUTPUT
  depoly:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Depoly the App
        run: echo "We are depolying the app with version ${{ needs.build.outputs.version }}"
      
